### ISSUE TITLE
Incompatible with Python 3.10 on Apple M1 

### ISSUE THREAD

**Issue by mopore** [Neradoc/discotool#10]
I run Python 3.10.5 (build from source) on an M1 and MacOS 12.4.
After installing discotool with `python3 -m pip install discotool` and calling `discotool` I receive the following error message:
```
`ImportError: dlopen(/opt/homebrew/lib/python3.10/site-packages/psutil/_psutil_osx.cpython-310-darwin.so, 0x0002): tried: '/opt/homebrew/lib/python3.10/site-packages/psutil/_psutil_osx.cpython-310-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e'))`
```
I uninstalled/installed 'psutil' but this did not solve the problem.

**Comment by Neradoc** [comment]
Hmmmm looks like psutil has no compatible version.
A cursory search for "psutil apple silicon" lands on that suggestion:
```
pip uninstall psutil
pip install --no-binary :all: psutil
```

**Comment by mopore** [comment]
Thanks, @Neradoc. I tried this (with and without setting the "-arch" flag to "arm64e") though it does not seem to take effect.

**Comment by mopore** [comment]
I removed the Python 3.10 installed with Homebrew and used the universal installer from python.org. This fixed my poblem!
